language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
after_success:
- export SSHPASS=$pwd
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- zip -r api.zip ./app
- sshpass -p $pwd scp ./api.zip $uid@123.207.14.113:/usr/local/source/distss/
- sshpass -p $pwd scp ./deploy.sh $uid@123.207.14.113:~/