language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_bd0bd10cde91_key -iv $encrypted_bd0bd10cde91_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- export SSHPASS=$pwd
- zip -r api.zip ./app
- sshpass -e scp ./api.zip $host:/usr/local/source/distss/
- sshpass -e scp ./package.json $host:/usr/local/source/distss/
- sshpass -e scp ./deploy_api.sh $host:/usr/local/source/distss/
- sshpass -e ssh $host 'cd /usr/local/source/distss && sh deploy_api.sh'
env:
  global:
  - secure: McskYIW/g6ODpo8ANs9uTr75X8A89MoSSCW9JIUfbuhwCZVtvH9oq7QVrYL+YPCfu2SW5j7Q79U+Fa5O/kBKGrKPqaXpAaA+/U4N7OjxCwHDALSOkyBErEGNx15xPVw2TwZywKwSe66MJS6C34w3GLvv5EYhgh4hE2ZwAyZiVlpwothtfSe5MUr67tALIKCiK3dCv1FrVMWU5NZHK5Mie9JC/D4oWxaGm81QCnmosm76poVYdIcvRtH5EvOrsdEgnC4EYU3/r7kubn9Ku+9tOEA1L+AE2T2VLByURVoDuuydJUZF+jLdVBPe+fOuY7QMBkHXRBGJaLFbJIofyRlQDfQbb5nbW37WoOmt5FQVoh7bVtGuZ1IrlZUjeAKm6uL+QlxQ2YxJYfe7Q6eSeAzINXLaeoWreigO7hJ4ul2MNYMfAm8j6/BYoMcpBA9+NlhguSXjfp3FPIqsx6MBAY9/l1z9bjnoZLWKyLD+mIxEcSqyQeHPWd/Ax/gl9l/BmfOITLOU6oCsWRcI+e9o4o3lW/PTcnvGO7LyGu89DBz+UMIjPVwOdYhlNZGBZd7b53KaDP8o7y6kaT4+aOzhDtZrQt31+kKR3ISMyOAsxzeZ9r10eEv1jzG/biZMoKxft3J9EUdQd4eGbr5Ee/BN0rzSH8bHOT7KjIpuSqO0NaIU4Og=
  - secure: M0zsdLi5+C7V9x7gvFj5+7LBNB6ahozOqVpTM0I6D/YyykFERMeLb+VvZAyoDYmZDRgUMdav5plxQMjmGgBmmH2B03L0laSTuIGTaB8gtshAJ9EciuX8PdgniVPKs8ODT/M/+OG8o5XacxEGVWJ3CooquUZxI04qeX1SSPPXSiwQpupU5QTn+snfPZSFvaIRhgm3cRCNVKmUnNkdOqVQrOvxlsgQKvLPrqBicWMVT0ZkbKGPo88xh7pz9W1l/bAboXAXFCwPx1hwz0tyUGzV0OHhKAKzvMYnG9tMyRH9jZIkZVZbO8WAX3mtTlDwQBfYgfpTPvzRm+Wy+LiBuMelKJbmjs8JpU4Xl1XtZJywhjiJBhT5zGFEQCE8+RAUYl/J4Ozu9PMQZ/Jhar+f9nhvvq0gDRROG6B8LRxJRaWfS5wRaORKDx7RSxYHTXYCsdTzExUknr/dHS9/0S/fMnrMZiRP8C36uphryd1EVVJ345y3jK0ptMgdOrLI4LekJcYfLj1ptrXH8r27e1QGx6EIHt1NKVumBupf1dOaxaIBsCDQoJq1O++j6kX/2olaFwWK71x0aJ1skyKbi/7kInFAgR1nXGQvAbkODioelfsrN8m4bdTj1J3y6GJFRl1wYY5+BXYnRBmY3EWoFs3AcUxHdYrUC7/GRsnCe68OdXT7eE4=
  - secure: tmJIXbL4VV9GHruO9MyoMv9+tEqbZKL+jVvjHXEAmVXAVBpFAxCsmdPgK2XYjY7xUZ6MMXNag2K2fxdnHwl1v7DV49tHiDOVDNcELKj6oC3mgJoEXWw1CAp+gXCWzaMq1BRq3iBv8dlbLk2A4TPRR9vvIB1+0dFRdji/dJMZrffoke0/+7aY2m3Xz6+VFciTYwWJ9dr4EMZKvqJmGIwIfvMN/L3UTgkQb0C/U19XHC3xCIrXhTT+OHGQdAOnDQ4kJuHNSwJNeW+grhXJkHQ/xXEjg0PA1owjV6b1H/Hz8TG8lJFu4IJUTMVvIluCinsIAmWT3gx6oxz5xwhkGn+EeMl5p9i2E/VuQ1yO/leGPM8znAeRgMA79kh2tqDDta90FNd3r4P9dUsNHyG7E9ShWoxSLnEh4CTrvhXZbGFmPWMYGQOM/7qZ/VQwfenlzQ21LYS7lZmUt+CXtI2oAG+E+zqWZhu0gdfPFfO4rtIcvVKhokao4K7bc1mUbTNGEPKXpoBqNJdBj0duxQ7/WdW828jdYJVdxzeoRcJMjXPI/TLAf6FzjqCA9z0wsEGvQ7RDLxfdFh9hB1jjh8+XP+wfrpgEfI4aai3frfhUz/yfHiTqObeSO7SH0ppmtgzR/r/m6s95WW3Npz3YRKKpS4nlLC84McaboTuZiKGYPI6ASS8=
