language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
after_success:
- export SSHPASS=$pwd
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- zip -r api.zip ./app
- sshpass -p $pwd scp ./api.zip $uid@123.207.14.113:/usr/local/source/distss/
env:
  global:
  - secure: VMgg/fEQJLq5UR98TAlDxTYbZcI3UG7470L87UCojckdZnOAh0c11IblaznPWPxfMtFYXIFPD+lTDSQ5UY4xoV+Ta8u7vbzeiOX2hxMtphaKCj3Jh9zRvpeXSG7vO2emWktUAGi3DdaiG8yQRzRGBkAyUR4a5UzGQcjxzgRYToE294JSJQFSMxYXXbULpPDqHVBGF4aNhv/GdtamRZzN/CmyygIsv81bbiv15Kn2YiB6rkbgWMPGAI1Uiu9ke9wV9ZR/4jqF3dYKASSNpf2vCYB0Ckejsh6JugqgfTlZxtzrR7aUuzpY9M+eE1wIIiRLdIXuEzgw+dh/eXM2fwPQdPT/a0pXVj/D2T4IdVPtU6IEeq645oyhim7NMEsEx0yCsgA4PCnViFZ/cuZNwHLFyqxnHl2/zakHhVYkwsSBRg1kM+teMXo6jzOYg6ljpp+uAFxy5I3VTaeiboZyBvjhne73EPccZaHB+IX1oXrcADgu1hB9brkcRSe8+j1GYVOJkCEsUMhm2e6LC232Hfa5pgH62VmcUhaHJeRBSmq+MY8psfOlm6yujPTiJTDIYFCVUasDqfdrN2GYLe8hgIYaBRZtm+hQBiIKJsTyXrSI3FrVqY8ptZNGwND1eFSC8n9KJOmQMrVFVhInBHNgTYKUzgXh8PGTk/bB/Co0bHnzdp8=
  - secure: XE/lyJo+aVoZKG3ZuUG0HKLST8/gFjmNSICgxmQs7/Ll5RnbnTFv9tvIphbtN2QeCE7Z54EtD0aVNAZgF7yMwSh/VAAlYGyQMMQ8KFPjIgGJEQ0vQ8A3kuS8QXDe1IFjdb5Qsyum7/gAZLLHGZa1nJawBY1kHIT3Br4uY9P0cUHgyT8G4jyDKSQ7V+g+nzFvUWqdSfssKa1/6qzuGRsNaqgDQ7fGFDL80dFo1ExRkjbH48HKxbBwSvMvLDK+s+4tRL+G8I4zI/Iv1P4KlMDB2gt07KCd0BVEpupljvegTEJrnyPGG566wcVsuqAqMJIY/5NLFEIaYI4WGov0DyFRbY0tORRCKisfIEl5n3p+k9iaBezrkpW1SPiUSu/es7jeeVCmi38hV1pJQ2zpTd1Pqm+QnV0cFaFDgUQtSWivpRyJohpTwZEnmKwfRhbTeq0QNpEz1FdEBFtKaGHVy1Iu2A9E1OelWesRYAbaXWAyzwl03Pa9Bg/Nb/86rRLgwSpVXLLhcURiPR6/yitYN1iLOwLRfwo1554zdn3IXEx88dnnnwoV9IiaohVfx6y/dV2Y39DpIw7QbNlKJ1JRn8CAis81xju1M74LXw/8HU8uOvw8Wcfv2/o5ugz3TqnObJZ7uL4VRnZOnaTsiVRNs6++5qzLviK4At+V3epU3nGlxBA=