language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_bd0bd10cde91_key -iv $encrypted_bd0bd10cde91_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- export SSHPASS=$pwd
- sshpass -e scp -P $port ./deploy_api.sh $host:/usr/local/source/distss/
- sshpass -e ssh -p $port $host 'cd /usr/local/source/distss && sh deploy_api.sh'
env:
  global:
  - secure: TBr+qOVQwmIv0E5PdiK9ktnSqfq9olmzjnDZaVFaaHDyWJ+uc3pGj/1VSPqlpLM5ebBKfG5zwBUF/SOwgVfe7EJbgTcYis7+iadV3vWfVJ9ls+/YhmyFOXPqAxHtOcLlQuYyN5RX0u+bc8r3tpVg1LBj5SUWQTOk1iS8uVw88UAF3KAFiYNLOc0MS1+QNHxVcmq/ssPpRGHG068uXN0wkh/3ZkZDaeb9o7qPWZP5QvKOo9xopiy6nPk6bAfxED6fJD4Bi1p5ONTDWYqoGEACi5pONI6h3b6j5mX01wndHPtMVNrmgpCtUVdqWnYX+x1YzybZGKcXMJBCFdTNBt2O9Ztn7R51n6aPEyQq4bsztWy7fn46C+UVX2QcqH++3DVf6YgDkjIWHqmhDwBgag5w5TPoSnhmDdC3DUE46DGxvu7xXMfdAYxichAYQAHxHBEzVWusH1aFJQkLTuEoBsxeHQ/RSZBxTD19KmPCIYKJCdNEZOXz0hXU7kb5TGCKvTLjcMOrOCErxup/fXxUMmfMqvMAr5ztufX4rouYKl58IWRwpW1EaMzwrhOBSNmKf7SrAqqeABJs1aRN5LNfGAcMeB49Mz/AKnJEYUlIcY3GirnyYvrp1ZHqQkPOQd8X18RS8aCXWR7GG7ZtqIGQKWGux/Nw0bMzj4HBELTByArbS3k=
  - secure: nJbGySQCEoiwH0HcuQnmmnYWXRgYgGHepdhayQmGSP7qH5P+Tw82UCzGdGJwucvQZyOt7RvspnBRINRaO/86udtdLN+pk279QNV/qA0y7+Sw21s/FstuiD1kLYXauYDsdsUTcHYvxUGt4BO1fQuDx5Ayw/digpXiDR8kkU2RKW9+1j54LxgsBkvT91pZPv2NtLXf5Lhl9pttSK7CWfVL9j46gtOxmSP/OM7fy9rLd70+G6kX8TsuKsIQkd94B5Ckwnujx+/t/IqxrXwSNukdaDTWlALmNIpjxMns5Iui/xTzGQy5NyCX6KLeofM+1XINIuRWSTr4BY3pQiVCmwNho/VZK0BjazX+6pilktmgrC4GKN1EcoW8iA/VpgU0o8gGBpNVjcEZvmA1peIYeEeq0EnYR5oaof5t76Avd/zXzMJuuHDoMa4cJ7E5uWGAxVroWvU22VkXH+h3j6KwDxV+s0uB4IGUoiFtSv55Q66gFmMMrijgyzsnHTS/cSx5XMvvSXFTSDoNyPSzSDhPBa9+7YpV07FppDUUBieVXeIYwkBoNiAoWIpUmy3gO3uXcihZdbvzZhrW6WDsF9PCDBoVroLSmFmpWRhFhRoCMpaM++0z3TTHJz1uSffKzpYTh/BHB64Y2Wi94dGeYjeSzbXCBNQnG6g2yp2ILOQzpEQjYnM=
  - secure: hoRK78RwlMLEVxQXBt+bWYQ6KY3KboIdYpungzdCGX+wwQz5R7Xt6L68Bw4SUcc3dL9XDSa//eoEISDJQDuzT8IOys6sBRjMsNbE1h3hD2wnrCynBF8YEnOe1b8OY8f6BY0nuU65qOFdL1tsDCxAsgKMLqmD1uOfSi2R+PxMjglg8Lab+V9d3IVONQ8zzj2eY6Uf99IUJRnLxkmLLYpA7p3Qcs2mN4ogtUpYFqiaaul++jUuBALZUCp4yIkuLMUevtHLb3+p1AvITuIevCyP3dZ4GZjY/JFp0tSvSkJL39liVoUiRveeD1UDyOB0HwB2T8Zwye0DLHIEspQGbh/USVU8nD3b1hKUw3391p5zxMl6d/nyDFjmPJnyNiKeD8VlibumeU4R995dQhW3v/HM9B02UDpvvQPIAl16IXB8YOg+GVx0DUQcgi1vq6ilfQMtQRPFHF+RA2yCdOdkZI/dvrOBqCwZg2Oxr1n4lXq4LhBS4R2TZqc9b/es5ylA7ZdN4J4nzu8Sl7bQhzkGtougvFhgLzxK6ceg3ATXIso0zP51Fz5NaK3r39NO4tzNWCIZcayRuAw5re3e0AE+8/N8eJ9M9vZe/LhN3PWDwOdBDD6U9b8oRBUXwKOlpbP67yn5NXdqkCUQYz4kUW2Sip40Golo+RQ9nRl2OltPM7++CDA=
